export type Field={key:string;label:string;type?:'text'|'number'|'date'|'select';options?:string[]};
export const fields:Record<string,Field[]>={
projects:[{key:'code',label:'Mã dự án'},{key:'name',label:'Tên dự án'},{key:'status',label:'Trạng thái',type:'select',options:['planning','active','on_hold','completed']},{key:'start_date',label:'Bắt đầu',type:'date'},{key:'end_date',label:'Kết thúc',type:'date'},{key:'budget',label:'Ngân sách',type:'number'},{key:'progress',label:'Tiến độ %',type:'number'}],
tasks:[{key:'project_id',label:'Project ID',type:'number'},{key:'title',label:'Công việc'},{key:'status',label:'Trạng thái',type:'select',options:['todo','in_progress','blocked','done']},{key:'priority',label:'Ưu tiên',type:'select',options:['low','medium','high','critical']},{key:'start_date',label:'Bắt đầu',type:'date'},{key:'due_date',label:'Hạn',type:'date'},{key:'progress',label:'Tiến độ %',type:'number'}],
schedule:[{key:'project_id',label:'Project ID',type:'number'},{key:'task_id',label:'Task ID',type:'number'},{key:'baseline_start',label:'Baseline start',type:'date'},{key:'baseline_finish',label:'Baseline finish',type:'date'},{key:'actual_start',label:'Actual start',type:'date'},{key:'actual_finish',label:'Actual finish',type:'date'}],
resources:[{key:'project_id',label:'Project ID',type:'number'},{key:'name',label:'Tên nguồn lực'},{key:'resource_type',label:'Loại',type:'select',options:['labor','equipment','subcontractor']},{key:'capacity_hours_week',label:'Giờ/tuần',type:'number'},{key:'cost_rate',label:'Đơn giá/giờ',type:'number'}],
boq:[{key:'project_id',label:'Project ID',type:'number'},{key:'code',label:'Mã BOQ'},{key:'description',label:'Mô tả'},{key:'unit',label:'Đơn vị'},{key:'quantity',label:'Khối lượng',type:'number'},{key:'unit_price',label:'Đơn giá',type:'number'},{key:'actual_quantity',label:'KL thực tế',type:'number'}],
contracts:[{key:'project_id',label:'Project ID',type:'number'},{key:'contract_no',label:'Số hợp đồng'},{key:'vendor',label:'Nhà thầu/NCC'},{key:'value',label:'Giá trị',type:'number'},{key:'status',label:'Trạng thái',type:'select',options:['draft','active','expired','closed']},{key:'signed_date',label:'Ngày ký',type:'date'},{key:'expiry_date',label:'Ngày hết hạn',type:'date'}],
documents:[{key:'project_id',label:'Project ID',type:'number'},{key:'document_no',label:'Số tài liệu'},{key:'title',label:'Tên tài liệu'},{key:'category',label:'Loại'},{key:'revision',label:'Revision'},{key:'status',label:'Trạng thái',type:'select',options:['draft','submitted','under_review','revised','approved','closed']},{key:'file_path',label:'Đường dẫn file'}],
quality:[{key:'project_id',label:'Project ID',type:'number'},{key:'kind',label:'Loại',type:'select',options:['RFI','NCR','INS','MATERIAL','INSPECTION']},{key:'number',label:'Số hồ sơ'},{key:'title',label:'Tiêu đề'},{key:'status',label:'Trạng thái',type:'select',options:['draft','submitted','under_review','rejected','approved','closed']},{key:'due_date',label:'Hạn xử lý',type:'date'}],
changes:[{key:'project_id',label:'Project ID',type:'number'},{key:'number',label:'Số VO/Claim'},{key:'title',label:'Tiêu đề'},{key:'change_type',label:'Loại',type:'select',options:['vo','claim','variation']},{key:'amount',label:'Giá trị',type:'number'},{key:'time_impact_days',label:'Ảnh hưởng ngày',type:'number'},{key:'status',label:'Trạng thái',type:'select',options:['draft','submitted','review','approved','rejected','closed']}],
collaboration:[{key:'project_id',label:'Project ID',type:'number'},{key:'entity_type',label:'Đối tượng'},{key:'entity_id',label:'Entity ID',type:'number'},{key:'body',label:'Nội dung'}],
automation:[{key:'project_id',label:'Project ID',type:'number'},{key:'name',label:'Tên quy tắc'},{key:'entity_type',label:'Đối tượng'},{key:'trigger_event',label:'Trigger'}]
};
